title: PCBCrew
description: Best China PCBA Company and Hardware Design Development Service
baseurl: ""
url: "www.pcbcrew.com"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

footer_links:
  - title: Contact Us
    url: /contact

header_links:
  - title: Home
    url: /
  - title: Team
    url: /team
  - title: About
    url: /about
  - title: Services
    url: /services

header_action_title: Contact Us
header_action_url: /contact

contacts:
  email: pcbcrew@outlook.com
  phone: (+86)13022481053
  address: Shenzhen, Guangdong 518100, CN

ga: "UA-XXXXXXXX-X"

sass:
  sass_dir: _sass
  style: compressed

theme_color: "#286FB7"
